### PR TITLE
feat: add cost tag for simple chart

### PR DESCRIPTION
**Pull request by chiayu-su**

### CODE REVIEW

**Comment by chiayu-su** [comment]
+ # Source: simple/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: hannah-test
+   namespace: hannah-lab
+   labels:
+     businessid: "000000042529042534"
+     app: hannah-test
+ spec:
+   strategy:
+     rollingUpdate:
+       maxSurge: 25%
+       maxUnavailable: 25%
+     type: RollingUpdate
+   selector:
+     matchLabels:
+       app: hannah-test
+   template:
+     metadata:
+       labels:
+         app: hannah-test
+     spec:
+       topologySpreadConstraints:
+         - labelSelector:
+             matchLabels:
+               app: hannah-test
+           maxSkew: 1
+           topologyKey: topology.kubernetes.io/zone
+           whenUnsatisfiable: ScheduleAnyway
+         - labelSelector:
+             matchLabels:
+               app: hannah-test
+           maxSkew: 1
+           topologyKey: kubernetes.io/hostname
+           whenUnsatisfiable: ScheduleAnyway
+       containers:
+       - name: hannah-test
+         image: "990090895087.dkr.ecr.ap-southeast-1.amazonaws.com/shopline/hannah-test:latest"
+         imagePullPolicy: IfNotPresent
+         env:
+         - name: CONTAINER_NAME
+           value: hannah-test
+         envFrom:
+         - configMapRef:
+             name: hannah-test-env
+         ports:
+         - name: hannah-test
+           containerPort: 80
+           protocol: TCP
+         livenessProbe:
+           httpGet:
+             path: /health_check
+             port: 80
+           initialDelaySeconds: 10
+           periodSeconds: 5
+           timeoutSeconds: 60
+         readinessProbe:
+           httpGet:
+             path: /health_check
+             port: 80
+           initialDelaySeconds: 10
+           periodSeconds: 5
+           timeoutSeconds: 30
+         resources:
+           limits:
+             memory: 500Mi
+           requests:
+             cpu: 100m
+             memory: 256Mi
+         lifecycle:
+           preStop:
+             exec:
+               command: ["sleep", "15"]
+       restartPolicy: Always
+       serviceAccountName: hannah-test-pod-service-account
+       dnsConfig:
+         options:
+           - name: ndots
+             value: "2"
+       terminationGracePeriodSeconds: 75
hannah-lab, hannah-test, HorizontalPodAutoscaler (autoscaling) has been added:
-
+ # Source: simple/templates/hpa.yaml
+ apiVersion: autoscaling/v2
+ kind: HorizontalPodAutoscaler
+ metadata:
+   name: hannah-test
+ spec:
+   minReplicas: 2
+   maxReplicas: 4
+   scaleTargetRef:
+     kind: Rollout
+     apiVersion: argoproj.io/v1alpha1
+     name: hannah-test
+   metrics:
+   - type: Resource
+     resource:
+       name: cpu
+       target:
+         type: Utilization
+         averageUtilization: 70
hannah-lab, hannah-test, Ingress (networking.k8s.io) has been added:
-
+ # Source: simple/templates/ingress.yaml
+ apiVersion: networking.k8s.io/v1
+ kind: Ingress
+ metadata:
+   name: hannah-test
+   labels:
+     businessid: "000000042529042534"
+   annotations:
+     cert-manager.io/cluster-issuer: letsencrypt-prod
+     kubernetes.io/ingress.class: nginx
+     nginx.ingress.kubernetes.io/backend-protocol: HTTP
+     nginx.ingress.kubernetes.io/proxy-body-size: 10m
+     nginx.ingress.kubernetes.io/ssl-redirect: "false"
+ spec:
+   tls:
+     - hosts:
+         - ""
+       secretName:
+   rules:
+     -
+       http:
+         paths:
+         - backend:
+             service:
+               name: hannah-test
+               port:
+                 name: hannah-test
+           path: /
+           pathType: ImplementationSpecific
hannah-lab, hannah-test, Rollout (argoproj.io) has been added:
-
+ # Source: simple/templates/rollout.yaml
+ apiVersion: argoproj.io/v1alpha1
+ kind: Rollout
+ metadata:
+   name: hannah-test
+   labels:
+     businessid: "000000042529042534"
+   annotations:
+     notifications.argoproj.io/subscribe.on-rollout-aborted.slack_webhook: ""
+     notifications.argoproj.io/subscribe.on-rollout-completed.slack_webhook: ""
+     notifications.argoproj.io/subscribe.on-rollout-updated.slack_webhook: ""
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app: hannah-test
+   workloadRef:
+     apiVersion: apps/v1
+     kind: Deployment
+     name: hannah-test
+   strategy:
+     canary:
+       canaryService: hannah-test-canary
+       stableService: hannah-test-stable
+       steps:
+       - setWeight: 25
+       - pause:
+           duration: 1s
+       - setWeight: 50
+       - pause:
+           duration: 1s
+       - setWeight: 75
+       - pause:
+           duration: 1s
+       - setWeight: 100
+
+       trafficRouting:
+         alb:
+           ingress: sharvis
+           rootService: sharvis
+           servicePort: 3000
+
+       scaleDownDelaySeconds: 60
hannah-lab, hannah-test, Service (v1) has been added:
-
+ # Source: simple/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: hannah-test
+   annotations:
+     null
+   labels:
+     businessid: "000000042529042534"
+ spec:
+   ports:
+   - name: "hannah-test"
+     port: 80
+     targetPort: 80
+     protocol: TCP
+   type: ClusterIP
+   selector:
+     app: hannah-test
hannah-lab, hannah-test-canary, Service (v1) has been added:
-
+ # Source: simple/templates/rollout.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: hannah-test-canary
+   labels:
+     businessid: "000000042529042534"
+ spec:
+   ports:
+   - name: "hannah-test"
+     port: 80
+     targetPort: 80
+     protocol: TCP
+   type: ClusterIP
+   selector:
+     app: hannah-test
hannah-lab, hannah-test-pod-service-account, ServiceAccount (v1) has been added:
-
+ # Source: simple/templates/serviceaccount.yaml
+ apiVersion: v1
+ kind: ServiceAccount
+ metadata:
+   annotations:
+     eks.amazonaws.com/role-arn: arn:aws:iam::990090895087:role/HannahTestServiceRoleTest
+   name: hannah-test-pod-service-account
hannah-lab, hannah-test-stable, Service (v1) has been added:
-
+ # Source: simple/templates/rollout.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: hannah-test-stable
+   labels:
+     businessid: "000000042529042534"
+ spec:
+   ports:
+   - name: "hannah-test"
+     port: 80
+     targetPort: 80
+     protocol: TCP
+   type: ClusterIP
+   selector:
+     app: hannah-test

**Comment by chiayu-su** [comment]
```
+ # Source: simple/templates/deployment.yaml
+ apiVersion: apps/v1
+ kind: Deployment
+ metadata:
+   name: hannah-test
+   namespace: hannah-lab
+   labels:
+     businessid: "000000042529042534"
+     app: hannah-test
+ spec:
+   strategy:
+     rollingUpdate:
+       maxSurge: 25%
+       maxUnavailable: 25%
+     type: RollingUpdate
+   selector:
+     matchLabels:
+       app: hannah-test
+   template:
+     metadata:
+       labels:
+         app: hannah-test
+     spec:
+       topologySpreadConstraints:
+         - labelSelector:
+             matchLabels:
+               app: hannah-test
+           maxSkew: 1
+           topologyKey: topology.kubernetes.io/zone
+           whenUnsatisfiable: ScheduleAnyway
+         - labelSelector:
+             matchLabels:
+               app: hannah-test
+           maxSkew: 1
+           topologyKey: kubernetes.io/hostname
+           whenUnsatisfiable: ScheduleAnyway
+       containers:
+       - name: hannah-test
+         image: "990090895087.dkr.ecr.ap-southeast-1.amazonaws.com/shopline/hannah-test:latest"
+         imagePullPolicy: IfNotPresent
+         env:
+         - name: CONTAINER_NAME
+           value: hannah-test
+         envFrom:
+         - configMapRef:
+             name: hannah-test-env
+         ports:
+         - name: hannah-test
+           containerPort: 80
+           protocol: TCP
+         livenessProbe:
+           httpGet:
+             path: /health_check
+             port: 80
+           initialDelaySeconds: 10
+           periodSeconds: 5
+           timeoutSeconds: 60
+         readinessProbe:
+           httpGet:
+             path: /health_check
+             port: 80
+           initialDelaySeconds: 10
+           periodSeconds: 5
+           timeoutSeconds: 30
+         resources:
+           limits:
+             memory: 500Mi
+           requests:
+             cpu: 100m
+             memory: 256Mi
+         lifecycle:
+           preStop:
+             exec:
+               command: ["sleep", "15"]
+       restartPolicy: Always
+       serviceAccountName: hannah-test-pod-service-account
+       dnsConfig:
+         options:
+           - name: ndots
+             value: "2"
+       terminationGracePeriodSeconds: 75
hannah-lab, hannah-test, HorizontalPodAutoscaler (autoscaling) has been added:
-
+ # Source: simple/templates/hpa.yaml
+ apiVersion: autoscaling/v2
+ kind: HorizontalPodAutoscaler
+ metadata:
+   name: hannah-test
+ spec:
+   minReplicas: 2
+   maxReplicas: 4
+   scaleTargetRef:
+     kind: Rollout
+     apiVersion: argoproj.io/v1alpha1
+     name: hannah-test
+   metrics:
+   - type: Resource
+     resource:
+       name: cpu
+       target:
+         type: Utilization
+         averageUtilization: 70
hannah-lab, hannah-test, Ingress (networking.k8s.io) has been added:
-
+ # Source: simple/templates/ingress.yaml
+ apiVersion: networking.k8s.io/v1
+ kind: Ingress
+ metadata:
+   name: hannah-test
+   labels:
+     businessid: "000000042529042534"
+   annotations:
+     cert-manager.io/cluster-issuer: letsencrypt-prod
+     kubernetes.io/ingress.class: nginx
+     nginx.ingress.kubernetes.io/backend-protocol: HTTP
+     nginx.ingress.kubernetes.io/proxy-body-size: 10m
+     nginx.ingress.kubernetes.io/ssl-redirect: "false"
+ spec:
+   tls:
+     - hosts:
+         - ""
+       secretName:
+   rules:
+     -
+       http:
+         paths:
+         - backend:
+             service:
+               name: hannah-test
+               port:
+                 name: hannah-test
+           path: /
+           pathType: ImplementationSpecific
hannah-lab, hannah-test, Rollout (argoproj.io) has been added:
-
+ # Source: simple/templates/rollout.yaml
+ apiVersion: argoproj.io/v1alpha1
+ kind: Rollout
+ metadata:
+   name: hannah-test
+   labels:
+     businessid: "000000042529042534"
+   annotations:
+     notifications.argoproj.io/subscribe.on-rollout-aborted.slack_webhook: ""
+     notifications.argoproj.io/subscribe.on-rollout-completed.slack_webhook: ""
+     notifications.argoproj.io/subscribe.on-rollout-updated.slack_webhook: ""
+ spec:
+   replicas: 1
+   selector:
+     matchLabels:
+       app: hannah-test
+   workloadRef:
+     apiVersion: apps/v1
+     kind: Deployment
+     name: hannah-test
+   strategy:
+     canary:
+       canaryService: hannah-test-canary
+       stableService: hannah-test-stable
+       steps:
+       - setWeight: 25
+       - pause:
+           duration: 1s
+       - setWeight: 50
+       - pause:
+           duration: 1s
+       - setWeight: 75
+       - pause:
+           duration: 1s
+       - setWeight: 100
+
+       trafficRouting:
+         alb:
+           ingress: sharvis
+           rootService: sharvis
+           servicePort: 3000
+
+       scaleDownDelaySeconds: 60
hannah-lab, hannah-test, Service (v1) has been added:
-
+ # Source: simple/templates/service.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: hannah-test
+   annotations:
+     null
+   labels:
+     businessid: "000000042529042534"
+ spec:
+   ports:
+   - name: "hannah-test"
+     port: 80
+     targetPort: 80
+     protocol: TCP
+   type: ClusterIP
+   selector:
+     app: hannah-test
hannah-lab, hannah-test-canary, Service (v1) has been added:
-
+ # Source: simple/templates/rollout.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: hannah-test-canary
+   labels:
+     businessid: "000000042529042534"
+ spec:
+   ports:
+   - name: "hannah-test"
+     port: 80
+     targetPort: 80
+     protocol: TCP
+   type: ClusterIP
+   selector:
+     app: hannah-test
hannah-lab, hannah-test-pod-service-account, ServiceAccount (v1) has been added:
-
+ # Source: simple/templates/serviceaccount.yaml
+ apiVersion: v1
+ kind: ServiceAccount
+ metadata:
+   annotations:
+     eks.amazonaws.com/role-arn: arn:aws:iam::990090895087:role/HannahTestServiceRoleTest
+   name: hannah-test-pod-service-account
hannah-lab, hannah-test-stable, Service (v1) has been added:
-
+ # Source: simple/templates/rollout.yaml
+ apiVersion: v1
+ kind: Service
+ metadata:
+   name: hannah-test-stable
+   labels:
+     businessid: "000000042529042534"
+ spec:
+   ports:
+   - name: "hannah-test"
+     port: 80
+     targetPort: 80
+     protocol: TCP
+   type: ClusterIP
+   selector:
+     app: hannah-test
```

**Comment by chiayu-su** [comment]
```
 helm diff upgrade api ../simple -f values.yaml -n ec-stg-106
 
ec-stg-106, api, Deployment (apps) has changed:
  # Source: simple/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api
    namespace: ec-stg-106
    labels:
+     businessid: "000000000011111111"
      app: api
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    selector:
      matchLabels:
        app: api
    template:
      metadata:
        annotations:
          "instrumentation.opentelemetry.io/container-names" : "api,memcached"
          "instrumentation.opentelemetry.io/inject-sdk" : "true"
        labels:
          app: api
      spec:
        topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                app: api
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
          - labelSelector:
              matchLabels:
                app: api
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodegroup
                  operator: In
                  values:
                  - ec-eks-staging-memory-node-autoscaling-group
-         podAffinity:
-           {}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - api
                  topologyKey: topology.kubernetes.io/zone
                weight: 100
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - api
                  topologyKey: kubernetes.io/hostname
                weight: 99
        containers:
        - name: api
          image: "332947256684.dkr.ecr.ap-southeast-1.amazonaws.com/shopline/api:staging_b8b7746"
          imagePullPolicy: IfNotPresent
          env:
          - name: CONTAINER_NAME
            value: api
          envFrom:
          - configMapRef:
              name: api-env
          - configMapRef:
              name: api-custom-env
          - secretRef:
              name: eso-api-env
          - secretRef:
              name: api-custom-env
          ports:
          - name: api
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health_check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 30
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 300m
              memory: 2Gi
          lifecycle:
            preStop:
              exec:
                command:
                - sleep
                - "0.1"
        - name: memcached
          image: "332947256684.dkr.ecr.ap-southeast-1.amazonaws.com/memcached:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: CONTAINER_NAME
            value: memcached
          envFrom:
          ports:
          - name: memcached
            containerPort: 11211
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
        restartPolicy: Always
        serviceAccountName: api-pod-service-account
        dnsConfig:
          options:
            - name: ndots
              value: "2"
        terminationGracePeriodSeconds: 1
ec-stg-106, api, Ingress (networking.k8s.io) has changed:
  # Source: simple/templates/ingress.yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: api
+   labels:
+     businessid: "000000000011111111"
    annotations:
      kubernetes.io/ingress.class: internal-nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
  spec:
    rules:
      -
        host: "sa106.shoplinestg.com"
        http:
          paths:
          - backend:
              service:
                name: api
                port:
                  name: api
            path: /
            pathType: ImplementationSpecific
ec-stg-106, api, Service (v1) has changed:
  # Source: simple/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: api
    annotations:
      null
-   labels:
-     null
+   labels:
+     businessid: "000000000011111111"
  spec:
    ports:
    - name: "api"
      port: 80
      targetPort: 8080
      protocol: TCP
    type: ClusterIP
    selector:
      app: api
```

**Comment by chiayu-su** [comment]
```
helm diff upgrade shop ../simple -f values.yaml -n ec-stg-106

ec-stg-106, app-proxy, Service (v1) has changed:
  # Source: simple/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: app-proxy
    annotations:
      null
-   labels:
-     null
+   labels:
+     businessid: "000000000011111111"
  spec:
    type: ExternalName
    externalName: app-proxy-ec10-test-ps.cn2-gsoul.svc
ec-stg-106, shop, Deployment (apps) has changed:
  # Source: simple/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: shop
    namespace: ec-stg-106
    labels:
+     businessid: "000000000011111111"
      app: shop
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    selector:
      matchLabels:
        app: shop
    template:
      metadata:
        annotations:
          "instrumentation.opentelemetry.io/container-names" : "shop,memcached"
          "instrumentation.opentelemetry.io/inject-sdk" : "true"
        labels:
          app: shop
      spec:
        topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                app: shop
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
          - labelSelector:
              matchLabels:
                app: shop
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodegroup
                  operator: In
                  values:
                  - ec-eks-staging-memory-node-autoscaling-group
-         podAffinity:
-           {}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - shop
                  topologyKey: topology.kubernetes.io/zone
                weight: 100
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - shop
                  topologyKey: kubernetes.io/hostname
                weight: 99
        containers:
        - name: memcached
          image: "332947256684.dkr.ecr.ap-southeast-1.amazonaws.com/memcached:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: CONTAINER_NAME
            value: memcached
          envFrom:
          ports:
          - name: memcached
            containerPort: 11211
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
        - name: shop
          image: "332947256684.dkr.ecr.ap-southeast-1.amazonaws.com/shopline/shop:staging_c7e9323"
          imagePullPolicy: IfNotPresent
          env:
          - name: CONTAINER_NAME
            value: shop
          - name: SHOP_VERSION
            value: "3.229.0-68-gc7e9323"
          envFrom:
          - configMapRef:
              name: shop-env
          - configMapRef:
              name: shop-custom-env
          - secretRef:
              name: eso-shop-env
          - secretRef:
              name: shop-custom-env
          ports:
          - name: shop
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health_check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 30
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 1.5Gi
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
        restartPolicy: Always
        serviceAccountName: shop-pod-service-account
        dnsConfig:
          options:
            - name: ndots
              value: "2"
        terminationGracePeriodSeconds: 75
ec-stg-106, shop, Ingress (networking.k8s.io) has changed:
  # Source: simple/templates/ingress.yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: shop
+   labels:
+     businessid: "000000000011111111"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-wildcard
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
  spec:
    tls:
      - hosts:
        secretName: ss100-198.shoplinestg.com-tls-cert
    rules:
      -
        host: "ss106.shoplinestg.com"
        http:
          paths:
          - backend:
              service:
                name: shop
                port:
                  name: shop
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /product-v2/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /page-v2/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /about-v2/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /storefront-packs/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront-api
                port:
                  number: 80
            path: /storefront-api/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: shopperapp
                port:
                  number: 80
            path: /shopperapp/
            pathType: ImplementationSpecific
      -
        host: "*.ss106.shoplinestg.com"
        http:
          paths:
          - backend:
              service:
                name: shop
                port:
                  name: shop
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /product-v2/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /page-v2/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /about-v2/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront
                port:
                  name: storefront
            path: /storefront-packs/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: storefront-api
                port:
                  number: 80
            path: /storefront-api/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: shopperapp
                port:
                  number: 80
            path: /shopperapp/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: app-proxy
                port:
                  number: 80
            path: /apps/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: app-proxy
                port:
                  number: 80
            path: /a/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: app-proxy
                port:
                  number: 80
            path: /community/
            pathType: ImplementationSpecific
          - backend:
              service:
                name: app-proxy
                port:
                  number: 80
            path: /tools/
            pathType: ImplementationSpecific
ec-stg-106, shop, Service (v1) has changed:
  # Source: simple/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: shop
    annotations:
      null
-   labels:
-     null
+   labels:
+     businessid: "000000000011111111"
  spec:
    ports:
    - name: "shop"
      port: 80
      targetPort: 8080
      protocol: TCP
-   type: ClusterIP
+   type: ClusterIP
    selector:
      app: shop
ec-stg-106, shopperapp, Service (v1) has changed:
  # Source: simple/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: shopperapp
    annotations:
      null
-   labels:
-     null
+   labels:
+     businessid: "000000000011111111"
  spec:
    type: ExternalName
    externalName: svc-for-hktw.myshoplinestg.com
ec-stg-106, storefront-api, Service (v1) has changed:
  # Source: simple/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: storefront-api
    annotations:
      null
-   labels:
-     null
+   labels:
+     businessid: "000000000011111111"
  spec:
    type: ExternalName
    externalName: nginx.storefront-api.svc.cluster.local
```

**Review by Dose0128 — APPROVED** [review]

**Review by slmchen — APPROVED** [review]

**Comment by abelite-fang** [comment]
approve

**Pull request merged**
