### PR TITLE
feat(simple): add ingress default ssl policy

### PR DESCRIPTION
**Pull request by chiayu-su**

### CODE REVIEW

**Comment by chiayu-su** [comment]
for nginx:
```
✗ helm get values -n homepage-staging home-en > home.yaml
✗ helm diff upgrade home-en . -f home.yaml --allow-unreleased -n homepage-staging

  # Source: simple/templates/ingress.yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: home-en
    labels:
      businessid: "000000042493042706"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
+
```

**Comment by chiayu-su** [comment]
for singe ingress that already has ssl policy: 
```
helm diff upgrade home-en . -f home.yaml --allow-unreleased -n homepage-production
  # Source: simple/templates/ingress.yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: home-en
    labels:
      businessid: "000000042493042706"
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:332947256684:certificate/296b268a-c432-4086-8e71-c739d0f58bda
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "61"
      alb.ingress.kubernetes.io/healthcheck-path: /health_check
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "60"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true,access_logs.s3.enabled=true,access_logs.s3.bucket=aws-service-logs,access_logs.s3.prefix=elb/home-en-production
      alb.ingress.kubernetes.io/load-balancer-name: alb-home-en-production
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
      alb.ingress.kubernetes.io/tags: businessid=000000042493042706
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
+
```

**Comment by chiayu-su** [comment]
for single ingress that doesnt have ssl-policy setting:
```
  # Source: simple/templates/ingress.yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ben
    labels:
      businessid: "000000042509042512"
    annotations:
      alb.ingress.kubernetes.io/actions.both-hosts: |
        {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"ben","ServicePort":"ben"}]}}
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:332947256684:certificate/296b268a-c432-4086-8e71-c739d0f58bda
      alb.ingress.kubernetes.io/conditions.both-hosts: |
        [{"field":"host-header","hostHeaderConfig":{"values":["ben-preview-publisher.internal.shopline", "ben-preview-publisher.shoplineapp.com"]}}]
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: "16"
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "15"
      alb.ingress.kubernetes.io/healthy-threshold-count: "2"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=aws-service-logs,access_logs.s3.prefix=elb/ben-preview-internal-alb,deletion_protection.enabled=true,routing.http2.enabled=true
      alb.ingress.kubernetes.io/load-balancer-name: ben-preview-internal-alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/subnets: subnet-0179099309e35b8ef,subnet-08d263672e9403101
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
      kubernetes.io/ingress.class: alb
+
+     alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
```

**Comment by chiayu-su** [comment]
EnableMutilpleIngress=true (ingress_multiple) both doesnt have ssl-polict setting:

```
helm diff upgrade open-api-ruby . -f oa.yaml --allow-unreleased -n open-api
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: external
    labels:
      businessid: "000000042521042523"
    annotations:
...
+     alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
...
...
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: internal
 +     alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
```

**Review by littlesheng19 — APPROVED** [review]
LGTM

**Review by abelite-fang — APPROVED** [review]
LGTM

**Pull request merged**
